# vim: ft=yaml.ansible
---
- name: Check if cmdline.txt exists in /boot/firmware
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: firmware_cmdline

- name: Enable cgroup via boot commandline if not already enabled (new path)
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
  notify: Reboot
  when: firmware_cmdline.stat.exists

- name: Enable cgroup via boot commandline if not already enabled (old path)
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
  notify: Reboot
  when: not firmware_cmdline.stat.exists
